name: Daily Cloud ETL

on:
  schedule:
    - cron: '0 23 * * *'   # 06:00 s√°ng VN
  workflow_dispatch:

jobs:
  etl:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run cloud ETL
        run: python backend/etl/run_etl.py

      - name: Commit & push data
        run: |
          git config --global user.name "laihoangson"
          git config --global user.email "lson21757@gmail.com"
          git add data/
          git commit -m "Daily fetch & clean data" || echo "No changes"
          git push
